### ISSUE TITLE
Chrome 62 adds a default border radius to <button>

### ISSUE THREAD

**Issue by morkro** [necolas/normalize.css#706] opened 2017-10-18 10:49 UTC
Hello,

I have just updated to Chrome `62.0.3202.62` and discovered that they've added a default border radius of `4px` to all `<button>` and `input[type="button"]`. Is this something normalize.css should _normalize_ from now on?

Screenshot:
<img width="425" alt="screen shot 2017-10-18 at 11 48 19" src="https://user-images.githubusercontent.com/2461956/31715089-61204bd2-b3fa-11e7-88e5-762de859a3de.png">

**Comment by slavanga** [comment] 2017-10-18 18:55
This is interesting. I noticed two things:

1. The user agent stylesheet only changed on macOS. This makes sense because Windows generelly doesn’t have round buttons.
2. Even on macOS no border-radius is applied because of [line 281](https://github.com/necolas/normalize.css/blob/master/normalize.css#L281).

**Comment by morkro** [comment] 2017-10-18 20:39
> 2. Even on macOS no border-radius is applied because of line 281.
I can't confirm. Even with `-webkit-appearance: button;` they still have a rounded border in Chrome.

**Comment by kostasmanionis** [comment] 2017-10-24 09:39
For reference: https://www.chromestatus.com/features/5743649186906112

**Comment by mgol** [comment] 2017-10-27 09:14
A ticket about that that got wontfixed: https://bugs.chromium.org/p/chromium/issues/detail?id=752450

IMO it'd be good for normalize to reset `border-radius` on buttons. Note that people may set `-webkit-appearance: none` in their code for a specific button and they won't know their button now looks broken in Chrome for macOS (and only there). This sounds like a kind of thing that normalize.css should handle.

**Comment by adamduncan** [comment] 2017-10-29 11:52
PR for this issue here if it helps: https://github.com/necolas/normalize.css/pull/697

**Comment by tmair** [comment] 2017-11-06 10:30
The chrome team decided to revert the change: https://bugs.chromium.org/p/chromium/issues/detail?id=752450#c13

**Comment by cannikin** [comment] 2017-11-16 17:20
So I just got upgraded to Chrome 62 and all our buttons got rounded! I'm on macOS. See the two buttons on the right here (the first three are actually forms, not buttons):

![image](https://user-images.githubusercontent.com/300/32905643-5ddb6058-caaf-11e7-8ba1-42aee5ed8202.png)

**Comment by coreation** [comment] 2017-11-30 10:29
Any idea on what the gap is between them deciding to revert the change and actual chrom(ium) updates?

**Comment by mgol** [comment] 2017-11-30 12:51
@coreation It'll be included in Chrome 63, tentatively scheduled for Dec 5th. See https://www.chromium.org/developers/calendar

**Comment by hay** [comment] 2017-12-04 15:41
It seems the Chrome team has already (wisely IMO) decided to revert this change. Starting with Chrome 63 [buttons will have no `border-radius` again](https://bugs.chromium.org/p/chromium/issues/detail?id=752450#c13).

**Comment by garrettw** [comment] 2017-12-04 16:40
@hay If you had read the comments here before posting your own, you’d have realized that you’d be simply repeating what has already been mentioned.

**Comment by hay** [comment] 2017-12-04 16:50
@garrettw i read the comments before posting myself, i just didn't see it. But thanks for pointing that out.

**Comment by mgol** [comment] 2017-12-07 10:55
Chrome 63 has just been released.

**Comment by danielbarillo** [comment] 2017-12-07 13:31
I can confirm that updating Chrome from 62 to 63 fixes this issue!

**Comment by Warxcell** [comment] 2017-12-14 13:04
I'm with Version 63.0.3239.84 (Official Build) (64-bit) and the bug is existing for select.

![image](https://user-images.githubusercontent.com/3340882/33993528-8ef6ef5e-e0df-11e7-8747-0f3a5c077e51.png)

**Comment by mgol** [comment] 2017-12-14 13:14
Should it be closed?

**Comment by necolas** [comment] 2018-02-08 23:36
Thanks for the info

**Closed by necolas** 2018-02-08 23:36 UTC
