### ISSUE TITLE
Set input[type="search"] box sizing to border-box

### ISSUE THREAD

**Issue by oleersoy** [necolas/normalize.css#486] opened 2015-11-04 20:49 UTC
Having box-sizing set to `border-box` will it make it consistent with suitcss-base and bootstrap 4.  Both currently reset the box-sizing to `border-box`.

**Comment by patrickhlauke** [comment] 2016-01-19 09:58
dupe of https://github.com/necolas/normalize.css/issues/471 ?

**Comment by cvrebert** [comment] 2016-01-22 05:59
This has been fixed by fe567632afcf8afcf17925ab2a507ed87504cce8.

**Comment by jonathantneal** [comment] 2016-01-22 07:22
Indeed, and #496 was merged. Thanks for pointing that out! Closed.

**Closed by jonathantneal** 2016-01-22 07:22 UTC
Labels: bug
