### ISSUE TITLE
[Hidden] Attribute Issue With Table Elements

### ISSUE THREAD

**Issue by EuanMead** [necolas/normalize.css#361] opened 2014-08-16 12:59 UTC
Normalize breaks the hidden attribute being used to collapse table elements. Please see below examples.

[Fix as per spec](http://jsfiddle.net/ucdff9z1/)
[Normalize Rendering](http://jsfiddle.net/459Lct11/2/)

In the [HTML5 W3C Default Stylesheet](http://www.w3.org/TR/html5/rendering.html) note [hidden] attribute is defined as display:none, [see here](http://www.w3.org/TR/html5/rendering.html#hidden-elements). However in the [tables section](http://www.w3.org/TR/html5/rendering.html#tables) you can see that the [hidden] attributes are redefined.
```
table { display: table; }
caption { display: table-caption; }
colgroup, colgroup[hidden] { display: table-column-group; }
col, col[hidden] { display: table-column; }
thead, thead[hidden] { display: table-header-group; }
tbody, tbody[hidden] { display: table-row-group; }
tfoot, tfoot[hidden] { display: table-footer-group; }
tr, tr[hidden] { display: table-row; }
td, th, td[hidden], th[hidden] { display: table-cell; }

colgroup[hidden], col[hidden], thead[hidden], tbody[hidden],
tfoot[hidden], tr[hidden], td[hidden], th[hidden] {
  visibility: collapse;
}
```

The below code should be added:

```
/* Override display:none on [hidden] */
colgroup[hidden] { display: table-column-group; }
col[hidden] { display: table-column; }
thead[hidden] { display: table-header-group; }
tbody[hidden] { display: table-row-group; }
tfoot[hidden] { display: table-footer-group; }
tr[hidden] { display: table-row; }
td[hidden], th[hidden] { display: table-cell; }
/* Collapse these table elements */
colgroup[hidden], col[hidden], thead[hidden], tbody[hidden],
tfoot[hidden], tr[hidden], td[hidden], th[hidden] {
  visibility: collapse;
}
```

**Comment by Willem-Siebe** [comment] 2015-01-16 12:42
https://github.com/twbs/bootstrap/issues/15274

**Comment by jonathantneal** [comment] 2016-01-30 16:57
I find that `[hidden]` as `display: none` can be useful when removing or revealing elements from screen readers.

@EuanMead, I see the alternative styling for `[hidden]` listed in the [table elements spec](https://www.w3.org/TR/html5/rendering.html#tables). However, I see no browsers implementing this behavior, and that’s cause for concern. If they all object to it, and there is a [confirmed](http://www.richinstyle.com/test/tables/visibilitycollapse.html) [bug](https://bugs.webkit.org/show_bug.cgi?id=8735) in Chrome when this style is coupled with `col` or `colgroup`, then this appears to be a highly instable fix. However, I’d love to know if there is any reasoning from vendors against the recommended styling.

@Willem-Siebe, the spec says:

> ... a rule that applies 'display: block' to all elements will cancel the effects of the hidden attribute. Authors therefore have to take care when writing their style sheets to make sure that the attribute is still styled as expected.

In a sense, it is telling library authors to either use `:not([hidden])` when defining anything other than `display: none` on an element, or (worse yet) to reassign `display: none` in `&[hidden]`-type situations for old Internet Explorer. Normalize.css avoids unexpected selector weight, so this may not be something possible or fitting for us.

**Comment by jonathantneal** [comment] 2016-03-15 21:24
I’m closing this because no browsers are implementing this behavior to *normalize*, and the true fix is not be something possible in this library.

**Closed by jonathantneal** 2016-03-15 21:24 UTC

**Comment by naktinis** [comment] 2021-07-08 19:54
Using `[hidden] { display: none }` is incorrect. Note that browsers ignore the `hidden` attribute once any CSS that defines a display property for that element gets loaded. However, if you introduce the aforementioned rule, now it's no longer "any CSS", but "CSS with higher specificity".

The standard behaviour is useful, for example, for hiding content after HTML is rendered and before CSS is fetched and applied (hide the ugly flash of unstyled content). However, with the css-level `[hidden]...` that's no longer working as expected.

The behaviour I described is mentioned here:
https://html.spec.whatwg.org/dev/interaction.html#the-hidden-attribute
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
