### ISSUE TITLE
Homepage doesn't provide latest version

### ISSUE THREAD

**Issue by joshuajabbour** [necolas/normalize.css#489] opened 2015-11-22 05:54 UTC
http://necolas.github.io/normalize.css/ links to 3.0.2, not the latest version (3.0.3).

I'd create a pull request, but it looks like your `gh-pages` branch is created using some script that's not in the repo...

**Comment by GaetanBt** [comment] 2015-11-23 09:23
Already spotted in #457 :)

**Comment by joshuajabbour** [comment] 2015-11-23 19:43
Thanks, kinda hard to find with that title. :)

**Comment by GaetanBt** [comment] 2015-11-26 09:35
Yeah for sure, it was pretty hard for me to find it again :D

**Comment by cvrebert** [comment] 2016-01-23 03:23
@jonathantneal Please close as duplicate of #489?

**Comment by jonathantneal** [comment] 2016-01-23 04:40
Thank you, @cvrebert. Done.

**Closed by jonathantneal** 2016-01-23 04:40 UTC

**Comment by joshuajabbour** [comment] 2016-01-23 06:47
Um, #489 isn't a dupe of #489. This bug still exists...

**Comment by cvrebert** [comment] 2016-01-23 06:53
Oops. This is why I wish GitHub would repeat the issue number closer to the comment box.

**Comment by battaglr** [comment] 2016-01-23 12:07
With all the recent activity on this repo I noticed the same but didn't saw this issue, so I opened a PR for it on #503. I should have check more carefully... sorry @joshuajabbour. 😅
