### ISSUE TITLE
hgroup element removal

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [necolas/normalize.css#472] opened 2015-08-28 14:43 UTC
This was first raised over two years ago (here: #180). It's been raised several times since then: #268 #227 #316 #317. However, most of these are simply posts telling people to read #180. Things have changed since this was first raised, including the fact that the `hgroup` element has now been formally removed from the final HTML5 spec (http://www.w3.org/TR/html5/obsolete.html), so I thought I would try and raise a modern discussion about it.

The only argument I've read for keeping this obsolete element in Normalize.css is this: Some people have previously used it (before the HTML5 was finalised), and so future versions of Normalize.css should support these people. 

Personally, I think this seems backwards facing. I fully support attempts at pushing both users and developers to use modern tools and standards.

Regardless of what I think, however, I'd love to hear what others have to say.

Thanks a lot.

**Comment by Volker-E** [comment] 2015-08-28 22:18
:+1:

**Comment by Alhadis** [comment] 2015-08-29 05:41
Fully agreed.

**Comment by LasseRafn** [comment] 2015-08-31 11:10
I just realised it after looking at the code. I think removing it is the only correct thing to do.

**Comment by alwillis** [comment] 2015-09-02 05:04
A couple of points:
1. It may have been removed from W3C's spec for dubious reasons, it's still in [WHATWG's "Living Standard"](https://html.spec.whatwg.org/multipage/semantics.html#the-hgroup-element), updated September 1, 2015.

2. It's also on [Mozilla's HTML reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup), with this pragmatic note:

>This element has been removed from the HTML5 (W3C) specification, but it still is in the WHATWG version of HTML. It is partially implemented in most browsers, though, so is unlikely to go away. As the outline algorithm is not implemented in any browsers, the `hgroup` semantics are in practice only theoretical.

Translation: it's not hurting anybody; if it appears in markup, it's no big deal, so don't worry about it.

Personally, I'd just leave it alone…

**Comment by Volker-E** [comment] 2015-09-02 06:18
Hi @alwillis, what you're referring to as "Mozilla's HTML reference" is in it's fundamentals a wiki, where everybody can participate in and Mozilla might go over certain contributions or take care of certain articles in doubt. 
If you're looking into the [history of the article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup$history), the latest contribution, altering the paragraph that you're citing, comes from well-respected @stevefaulkner -- he was also participating in #180.

`hgroup` was *not removed by dubious*, **but for [good](http://www.iandevlin.com/blog/2013/04/html5/hgroup-removed-from-the-html5-specification) [reasons](https://lists.w3.org/Archives/Public/public-html-admin/2013Apr/0003.html).**

**Comment by alwillis** [comment] 2015-09-02 06:49
I don't want to rehash the whole thing; the point I was making is `hgroup` is still in WHATWG's living specification and that should count for something regarding what Normalize should address.

As a web developer, I’m familiar with @stevefaulkner and his work; however, I don't believe one person should be able to change what's supposed to be a global, open, and consensus-driven specification just because he disagrees with it.

**Comment by Volker-E** [comment] 2015-09-02 07:43
Ok, I wasn't by any means saying that one person should or is able to change a specification, nor does any of the links I've included. But your reference to MDN made it look like it's one of the places for looking for the definitive answer, whereas it is IMHO a consensus based collection of knowledge, partly clarified by employers of one of the big browser vendors.

For the decision here, it should be taken into account what 
1. the standard says (and that's for me preferably W3C over WHATWG *for historical reasons and for following points in this special case*),
2. the browser vendors implemented and
3. the vast majority of developers are using.

Otherwise normalize is handling a rare edge case, and that should be up to the single developers on rare edge cases.

**Comment by stevefaulkner** [comment] 2015-09-02 14:21
@alwillis On this point, which is an unecessary mischaracterisation: 
> I don't believe one person should be able to change what's supposed to be a global, open, and consensus-driven specification just because he disagrees with it.

&lt;hgroup> was removed by consensus, it was not added by consensus, The whatwg spec is by design NOT developed via consensus, so please take the time to understand reality before making such assertions.

In regards to including CSS rules for hgroup in normalize.css, I see no issue, note that although it is obsolete in HTML5 the parsing rules and UA default CSS advice for it remains in the spec as do the rules for other other obsoleted elements such as &lt;font> or &lt;center>

**Comment by alwillis** [comment] 2015-09-02 20:53
>In regards to including CSS rules for hgroup in normalize.css, I see no issue, note that although it is obsolete in HTML5 the parsing rules and UA default CSS advice for it remains in the spec as do the rules for other obsoleted elements such as <font> or <center>

I agree with that no issue is caused by leaving `hgroup` in Normalize. If anything, leaving it in may prevent potential unexpected behavior in the future if a developer's CSS is based on the current version of Normalize styling `hgroup` as `display: block` in IE 8/9 upgrades to a version of Normalize missing `hgroup` styling.

**Comment by JohnnyWalkerDesign** [comment] 2015-09-04 10:40
Thanks to all the responses. They make interesting reading.

> In regards to including CSS rules for hgroup in normalize.css, I see no issue, note that although it is obsolete in HTML5 the parsing rules and UA default CSS advice for it remains in the spec as do the rules for other obsoleted elements such as <font> or <center>

I don't quite follow the logic here. Should we include of `<font>` and `<center>` in Normalize.css? I understand the argument that keeping `hgroup` that "does no harm", but personally I think it's imperative that industry standard tools (like Normalize.css) push their users to adopt the latest standards. Standards are what help us embrace and develop using new technologies quickly, and without issue. The push for the standardisation of HMTL is what has lifted us out of the Internet Explorer doldrums of yesteryear, and I have no desire to return to them. 

Although I acknowledge there is no real world harm at the moment, I do think that allowing developers to decide for themselves which elements they wish to use, regardless of their status within agreed standards, is step backwards. It does not help the industry, other developers, or ultimately, their customers.

Just my personal view on the matter.

**Comment by alwillis** [comment] 2015-09-04 20:12
Providing styling for a hgroup, an element previously standardized by W3C and is still a recognized element by the most current WHATWG HTML 5.1 living standard is nothing like providing styling for FONT or any of the other proprietary tags put forth by Microsoft and Netscape back in the day.

Normalize is supposed to be about giving developers a consistent starting point for CSS across a wide variety of browsers; not about the politics of browser standards or telling developers what they should and shouldn’t do.

Normalize styles hgroup as a block element for browsers that don't themselves provide styling in the UA’s default stylesheet even when hgroup was fully supported by all standards bodies. That’s it.

And there’s nothing about that prevents developers from using current or future standards.

Providing styling for hgroup is just being thorough while proving for compatibility with both recognized HTML standards while not interfering anything else that might become a standard in the future. 

  —  Al

**Comment by stevefaulkner** [comment] 2015-09-04 21:21
> most current WHATWG HTML 5.1 living standard

you are getting your specs mixed up

the WHATWG HTML standard is unversioned

The latest W3C HTML specification working draft is 5.1 http://www.w3.org/TR/html51/
and in it &lt;hgroup> is still obsolete.

As a side note I recently [raised](https://github.com/whatwg/html/issues/83) a related issue on the WHATWG HTML spec in regards to the outline algorithm and there is suggestion that the algorithm and the section element will be dropped from the WHATWG HTML along with hgroup (as it was added to support the algorithm).

**Comment by alwillis** [comment] 2015-09-04 21:40
>you are getting your specs mixed up

>the WHATWG HTML standard is unversioned

>The latest W3C HTML specification working draft is 5.1 http://www.w3.org/TR/html51/
and in it <hgroup> is still obsolete.

True—the WHATWG HTML standard isn’t versioned; what I meant was as of today, `hgroup` is in [WHATWG’s HTML standards document](https://html.spec.whatwg.org/multipage/semantics.html#the-hgroup-element).

To me, the issue isn’t so much about that; Normalize is supposed to give a sane staring point for styling CSS across different browsers, including applying `display: block` to elements in some browsers that neglected to do that in their default stylesheets. That’s it.

**Comment by alwillis** [comment] 2015-09-05 02:47
>Standards are what help us embrace and develop using new technologies quickly, and without issue. The push for the standardisation of HMTL is what has lifted us out of the Internet Explorer doldrums of yesteryear, and I have no desire to return to them.

It’s kind of disingenuous and misguided to suggest setting `hgroup` to `display: block`—something every current browser’s default stylesheet does—in Normalize is the path that leads back to the days of the wild west of browser standards.

Since the most current versions of Chrome, Firefox, IE 11, Edge and Safari all set `hgroup` to `display: block`, it’s probably okay that Normalize does it for browsers like IE 8 and 9, which should have done the same thing but neglected to do when they were released. IE 8 and 9 are still over 10% of global browser use.

`hgroup` haters—don’t worry; if things stay on the their current path, even WHATWG will eventually disavow `hgroup` and a year or two after that, Google, Mozilla, Microsoft and Apple will remove support for it from their codebases. But we’re not there yet.

**Comment by stevefaulkner** [comment] 2015-09-05 03:02
>hgroup haters—don’t worry; if things stay on the their current path, even WHATWG will eventually disavow hgroup and a year or two after that, Google, Mozilla, Microsoft and Apple will remove support for it from their codebases and Normalize 5.0 (or whatever) can drop it too. But we’re not there yet.

Hi Al, please tone down the rhetoric, it's not helpful. You appear to misunderstand how standards and implementations in browsers work, even if the whatwg spec obsoletes hgroup, browsers will not remove default styling and parser support for it as long as there are statistically significant instances of its use on the web, the same as for the many other elements and attributes that have been implemented in browsers and later been made obsolete in HTML

**Comment by alwillis** [comment] 2015-09-05 05:12
>You appear to misunderstand how standards and implementations in browsers work…

Appearances can be deceiving.

Steve, I was just being sarcastic; I know the default styling and parsing won’t change, for example, as I may have  implied in my mini-rant. But I also didn’t expect it to be taken literally either. Before I became a full-time web developer, I worked many years in MIT’s main IT organization; believe me, I get what means to change the support status of something and the the details regarding that.

What you didn’t mention is what I wrote in all seriousness that was intended to understood as I wrote it, which was is factual and not sarcasm:

>Since the most current versions of Chrome, Firefox, IE 11, Edge and Safari all set hgroup to display: block, it’s probably okay that Normalize does it for browsers like IE 8 and 9, which should have done the same thing but neglected to do when they were released. IE 8 and 9 are still over 10% of global browser use.

Hopefully we can move on from this now?

**Comment by jonathantneal** [comment] 2015-09-05 05:30
Since `<hgroup>` has already been deprecated in both specifications, Normalize.css can deprecate `<hgroup>` in the next release, and then remove it in the release after that. It will be resolved and handled in a responsible, semver fashion.

If there is an issue with how things are deprecated or removed from Normalize.css, I think it’s fair to create a new issue for that. If there is an issue with the spec, that is pretty out of scope for Normalize.css to resolve.

**Comment by battaglr** [comment] 2015-09-05 05:49
> If there is an issue with how things are deprecated or removed from Normalize.css, I think it’s fair to create a new issue for that. If there is an issue with the spec, that is pretty out of scope for Normalize.css to resolve.

Thank you!

**Comment by alwillis** [comment] 2015-09-05 06:15
> On Sep 5, 2015, at 1:30 AM, Jonathan Neal <notifications@github.com> wrote:
> 
> Since <hgroup> has already been deprecated in both specifications, Normalize.css can deprecate <hgroup> in the next release, and then remove it in the release after that. It will be resolved and handled in a responsible, semver fashion.
> 
In all seriousness, how can you say that when it’s clearly still in the WHATWG specification: https://html.spec.whatwg.org/multipage/semantics.html#the-hgroup-element. There’s not even a note or a warning suggesting it might be removed at some point. Just saying.

**Comment by LasseRafn** [comment] 2015-09-05 07:27
Okay, let's just remove this issue, seems like we're going nowhere. I'll personally just continue to remove it from Normalise whenever I use it; mainly because I NEVER - in my entire life - used <hgroup>

**Comment by JohnnyWalkerDesign** [comment] 2015-09-05 11:00
> Providing styling for a hgroup, an element previously standardized by W3C and is still a recognized element by the most current WHATWG HTML 5.1 living standard is nothing like providing styling for FONT or any of the other proprietary tags put forth by Microsoft and Netscape back in the day.

The FONT element is actually a valid part of the W3G HTML 3 specification. Conversely HGROUP has never been part of any HTML specification. It was featured in a draft of HTML 5 (used by many eager developers wanting to move on from XHTML, with the knowledge that the specification wasn't finished), but dropped before finalisation. It has *never* been standardised HTML.

**Comment by alwillis** [comment] 2015-09-05 16:35
>It has never been standardised HTML.

And yet here’s a description of `<hgroup>`, as plain as day, in section [4.3.7 of the most current WHATWG specification](https://html.spec.whatwg.org/multipage/semantics.html#the-hgroup-element).

![hgroup](https://cloud.githubusercontent.com/assets/133189/9700244/ebe1cdec-53c9-11e5-959e-0afd379ebfb8.png)

And for something that you claim has never been standard HTML, Chrome 45, Firefox 40, Safari 9.0 and Edge provide styling for `<hgroup>` in their default stylesheets.

**Comment by JohnnyWalkerDesign** [comment] 2015-09-05 18:25
Sorry Al, I miswrote in my last post. My apologies. I was on my phone and should have waited until I was back at my desk. I meant to say that `<hgroup>` has never been part of the finalised HTML5 specification. As you have already correctly pointed out in this discussion, it does exist in the WHATWG "Living Standard" specification of HTML (note the lack of a version number -- WHATWG does not recognize different versions of HTML as part of its spec). It has never been part of HTML5 (the standard set down by the W3C -- note the version number), however.

I suppose if you subscribe to the WHATWG version of HTML, then `<hgroup>` is still valid. As a developer, however, I think most of us follow the W3G spec as it is doesn't change as frequently, allowing for things to be clearly defined long enough for us to use them without too much worry about UA support. (Likewise, if I were developing a browser, I suppose I would look to the WHATWG specification to see where things might be heading.)

**Closed** 2016-01-05 05:35 UTC
