### ISSUE TITLE
abbr tag shows double underline in firefox 40

### ISSUE THREAD

**Issue by hanakin** [necolas/normalize.css#470] opened 2015-08-26 15:42 UTC
Firefox updated default spec to include a text decoration underline on the abbr which conflicts with the border applied by normalize. suggest setting text-decoration:none on abbr

**Comment by 7studio** [comment] 2015-08-27 08:27
Duplicate of https://github.com/necolas/normalize.css/pull/451 and https://github.com/necolas/normalize.css/pull/468.

**Comment by cvrebert** [comment] 2016-01-23 03:16
@jonathantneal Please close as a duplicate?

**Comment by jonathantneal** [comment] 2016-01-23 04:32
@cvrebert, thanks! Done.

**Closed by jonathantneal** 2016-01-23 04:32 UTC
