### ISSUE TITLE
box-sizing issue with input[type="search"]

### ISSUE THREAD

**Issue by patrickhlauke** [necolas/normalize.css#471] opened 2015-08-28 09:01 UTC
```
-webkit-box-sizing: content-box;
box-sizing: content-box;
```

appears to be making search inputs wider than they should be - see https://github.com/twbs/bootstrap/issues/17379

**Comment by BYODKM** [comment] 2015-09-01 05:27
#358

**Comment by patrickhlauke** [comment] 2015-09-01 18:43
So, maybe @necolas can confirm (as I just read through the linked issues there, with their very terse comments): is the fact that `box-sizing: content-box` results in search inputs being larger than their equivalent text inputs intentional then, and won't be fixed? /cc @cvrebert

**Comment by BYODKM** [comment] 2015-09-02 01:14
Normalize.css is for normalize browsers' default style. Which means you can not always get what you want. You can have a small reset css for `input[type=search]` in your own project as usual.

**Comment by patrickhlauke** [comment] 2015-09-02 18:39
How about normalizing it to what should be the default, according to https://www.w3.org/Bugs/Public/show_bug.cgi?id=28784 ? I'm fine overriding it myself, but effectively here you're normalizing it against all current consistent (with exception of Firefox, but that's being fixed now too) default styling in browsers...

**Comment by FagnerMartinsBrack** [comment] 2015-09-02 23:26
I am watching this repository for a long time, and as far as I know there was no discussion regarding search inputs being wider than they should be. Most discussions regarding that style is about it being harder to override, because one can't just include normalize and go for `* { box-sizing: border-box; }` and expect the search inputs to be overriden.

Other than that this seems pretty legit and worth looking into, as long as it doesn't cause a regression from the [first bullet point](https://github.com/necolas/normalize.css/blob/3.0.3/normalize.css#L352).

**Comment by patrickhlauke** [comment] 2016-01-04 20:53
As there seems to be little interest here in addressing this, closing. We fixed it back to browser defaults in Bootstrap, FWIW.

**Comment by necolas** [comment] 2016-01-05 05:01
Sorry for being absent. I agree that this is an annoying quirk of normalize that should be fixed. It looks like the original reasoning doesn't stand up, and I'd rather be pragmatic about it anyway.

**Comment by patrickhlauke** [comment] 2016-01-05 11:33
Sorry for interpreting silence for lack of interest/agreement. Wasn't sure how best to formulate a visual test, but gave it a go in the PR anyway.

**Closed** 2016-01-21 21:49 UTC
