### ISSUE TITLE
Image input with inconsistent display mode in Firefox

### ISSUE THREAD

**Issue by visicode** [necolas/normalize.css#546] opened 2016-03-21 01:19 UTC
Firefox sets image inputs display as inline, and not inline-block like other browsers
Should be:
[type="image"] {
	display: inline-block;	/* FF */
}

**Comment by Yapaslfeu** [comment] 2016-04-11 01:07
Simply check User Agent stylesheets

**Comment by jonathantneal** [comment] 2016-04-11 03:22
That’s interesting. Firefox treats `<input type="image">` like `<img>` where it gains `inline-block` like behavior once an image is loaded. See http://s.codepen.io/jonneal/debug/9f6e462527d0f57c838af7617102f79a

**Comment by Yapaslfeu** [comment] 2016-04-11 07:56
Should be forced, isn't it?
I had some alignments problems without it…

**Comment by jonathantneal** [comment] 2016-06-01 02:33
This would be better bundled into opinionated stylesheets until such a time as something like the [`:loaded`](https://gist.github.com/bastianallgeier/1422798) pseudo-selector exists.

**Comment by KIPdeKIP** [comment] 2016-06-07 13:11
After applying `display: inline-block` Firefox still has vertical alignment issues.
See https://s.codepen.io/KIPdeKIP/debug/yJYowB
<a href="https://s.codepen.io/KIPdeKIP/debug/yJYowB"><img src="https://i.imgur.com/4j35a93.png" alt="Vertical alignment issues" title="Vertical alignment issues"></a>

**Comment by thierryk** [comment] 2016-06-07 15:58
> After applying display: inline-block Firefox still has vertical alignment issues.

`vertical-align` should help:

```
[type="image"] {
    vertical-align: bottom;
}
```

Not perfect tough as the above won't align the box to the baseline. 

As a side note, I prefer how Firefox deals with missing images. It makes sense to me that these boxes behave as _inline_ boxes when they are replaced by `alt` text and are only styled as `inline-block` when they are _replaced_ with an image. This behavior makes documents **easier to read** when images are not available.

**Comment by KIPdeKIP** [comment] 2016-06-10 14:24
@thierryk I don't agree with that. Elements should be consistent in how they display. A single image failing to load could ruin a website's layout just because the browser decided it was better this way.

Aside from that,
I've managed to cause a similar vertical alignment issue in Chrome as well with `<input type="image" src="data:;,">`. Here's how that looks in both Chrome and Firefox:

---

<h3>Before applying <code>vertical-align: bottom</code>:</h3>

| Chrome | Firefox |
| --- | --- |
| <img src="https://i.imgur.com/lMm8zD1.png" alt="Chrome Before" title="Chrome Before"> | <img src="https://i.imgur.com/YI5dhFr.png" alt="Firefox Before" title="Firefox Before"> |

https://s.codepen.io/KIPdeKIP/debug/aZdGPO

---

<h3>After applying <code>vertical-align: bottom</code>:</h3>

| Chrome | Firefox |
| --- | --- |
| <img src="https://i.imgur.com/wnqYvTm.png" alt="Chrome After" title="Chrome After"> | <img src="https://i.imgur.com/IQejVFY.png" alt="Firefox After" title="Firefox After"> |

https://s.codepen.io/KIPdeKIP/debug/rLxvEN

---

The inputs from left-to-right are: "no image", "valid image" and "empty data uri".

**Comment by thierryk** [comment] 2016-06-11 03:09
@KIPdeKIP 

> A single image failing to load could ruin a website's layout just because the browser decided it was better this way.

As far as I know, Firefox does this only for `input[type="image"]`, not for `img`, so I don't think it is *that* bad. 

> I've managed to cause a similar vertical alignment issue in Chrome as well with <input type="image" src="data:;,">

Actually, according to [specs](https://www.w3.org/TR/html5/forms.html#image-button-state-(type=image)):

> The `src` attribute must be present, and must contain a valid non-empty URL potentially surrounded by spaces referencing a non-interactive, optionally animated, image resource that is neither paged nor scripted.

Note that Firefox will submit coordinate `(0,0)` if the image fails to load&mdash;which shows that there is more to it than just visual issues.

**Comment by KIPdeKIP** [comment] 2016-06-11 06:58
@thierryk As long as the URL is valid the browser will parse it. `data:;,` is not a valid image and the browser should display it as such. Chrome displaying it differently is nonsense. Having to break the spec to cause it makes it a nonissue imo though.

The main issue is [this](https://s.codepen.io/KIPdeKIP/debug/gMPKgj). Firefox displaying `input[type="image"]` wrong when the image fails to load. (Timeout in this case.)

Even though there's more going on then just visual issues it should still be normalized right?

**Comment by thierryk** [comment] 2016-06-12 19:43
@KIPdeKIP 

I think we all agree about normalizing `input` via `display:inline-block` but I don't think we can do much beyond that&mdash;like trying to address the vertical alignment issue. 

From my understanding, Firefox display the *alternate* text using `::before` but Chrome uses the shadow DOM to display a broken image (via `alttext-container`).

The result of this is that Firefox treats the control as a **inline element** while browsers displaying a broken image treat that same control as a **inline-replaced element** which creates discrepancies between browsers, mostly issues related to dimensions, padding, and vertical alignment.

The vertical alignment issue that your examples show is the result of these elements being aligned to the **baseline**. The problem is that in Firefox it is the text that is aligned to the baseline, while in other browsers it is the bottom of the (broken) image.

Unfortunately, I don't think we can *normalize* the vertical alignment for these controls because that could influence the styling of surrounding elements (depending on their nature and their own vertical alignment). 

I hope this makes sense.

**Comment by KIPdeKIP** [comment] 2016-06-12 22:22
@thierryk

I can agree on that. Applying `vertical-align` isn't worth the trouble. 

If anything gets merged for this it should mention the alignment issue though. Either in the README or with ["Known issue:"](https://github.com/necolas/normalize.css/blob/857aa8bfd433a8b0457b4df6ac882dc072d37220/normalize.css#L50) like v1 did.

**Comment by jonathantneal** [comment] 2016-07-04 00:03
Unfortunately, `display: inline-block; vertical-align: baseline;` is not enough to normalize these elements without breaking from any default browser behavior. If someone would like to make a PR to add a note for this to the known issues section, I will accept it.

**Closed by jonathantneal** 2016-07-04 00:03 UTC
Labels: request
